language: java
jdk:
- oraclejdk7
sudo: required
services:
- docker
- docker-compose

install:
- sudo apt-get update
- sudo apt-get install -y supervisor

- mvn package -DskipTests=true -Dmaven.javadoc.skip=true -B -V -Pmock
- sudo chmod a+rwx ./target/*
- supervisord -c ./conf/supervisord.conf
#- java -jar ./target/mock-server-jar-with-dependencies.jar
- ls -alR ./target/*
- ps -ef | grep java
- cat ./target/mock-server.log
- netstat -ano