language: java
jdk:
- oraclejdk7
sudo: required
services:
- docker
- docker-compose
os:
- linux

install:
- sudo apt-get update
- sudo apt-get install -y supervisor

- mvn package -DskipTests=true -Dmaven.javadoc.skip=true -B -V -Pmock
- sudo chmod a+rwx ./target/*
#- ls /etc/*
- sudo whereis supervisord.conf
- sudo cp ./conf/supervisord.conf /etc/supervisor/
- cat /etc/supervisor/supervisord.conf
- supervisorctl -h
- supervisord -h
- sudo service supervisor force-reload
- echo "`pwd`test"
#- supervisord
- sh startup.sh
#- ls -alR ./target/*
- ls -alR $HOME/*
- ps -ef | grep java
- netstat -ano
- netstat -ano | grep 19999